<Project>
  <PropertyGroup>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <DaxAlgoSdkVersion>0.3.0-alpha</DaxAlgoSdkVersion>
  </PropertyGroup>
</Project>
