using System.IO;
using System.Reflection;
using System.Text;
using System.Xml.Linq;
using DaxAlgo.Sdk;

namespace TradingTerminal.Infrastructure.Strategies.Authoring;

/// <summary>
/// Emits the authoring contract surface a model is given, <b>reflected from
/// <c>DaxAlgo.Sdk</c></b> rather than described by hand.
///
/// <para>This exists because the hand-maintained pack drifted badly: it taught
/// <c>IBacktestStrategy</c> nine times, <c>IStrategyKernel</c> once, and said nothing whatsoever
/// about <c>IRenderSurface</c> or <c>Draw</c> — so the one contract that puts pixels on screen was
/// invisible to the thing meant to generate against it. <c>StrategyContextPack</c>'s own doc records
/// how that happened: its generator, <c>build/gen-ai-context.ps1</c>, went missing and the markdown
/// was left to be maintained by hand.</para>
///
/// <para>The fix is to derive the facts and hand-write only the judgement. Signatures and summaries
/// come from the assembly and its XML documentation, so a contract change shows up here on the next
/// build; <c>SdkSurfaceFreshnessTests</c> fails when the committed copy falls behind. Prose about
/// <i>how to think</i> about the contracts stays hand-written, where it belongs.</para>
/// </summary>
public static class SdkSurfaceGenerator
{
    /// <summary>Where the generated surface is committed, relative to the repository root.</summary>
    public const string RelativePath = "sdk/ai-context/generated/sdk-surface.md";

    /// <summary>
    /// The authoring surface, in the order an author meets it: what you implement, what you draw
    /// onto, then the helpers and the vocabulary. Types outside this list are host wiring an author
    /// never touches, and including them would spend a model's attention on noise.
    /// </summary>
    private static readonly string[] Sections =
    [
        "What you implement",
        "What you draw onto",
        "Quant helpers",
        "Drawing helpers",
        "Vocabulary",
    ];

    /// <summary>
    /// Public types an author never names, and which are therefore left out entirely.
    ///
    /// <para>The section list above already says the intent — "types outside this list are host
    /// wiring an author never touches, and including them would spend a model's attention on noise" —
    /// but "Vocabulary" is a fallback that catches everything unmatched, so the intent was never
    /// enforced and every one of these shipped at full length in the system prompt.</para>
    ///
    /// <para>Three kinds of noise: the plugin entry points, which the compiler generates rather than
    /// the author (<c>AuthoredPluginBootstrap</c>, <c>IStrategyPlugin</c>, <c>IPluginRegistrar</c>,
    /// <c>PluginContext</c>, <c>AuthoredStrategyTypes</c>); the lifecycle interfaces, which the host
    /// implements and calls; and the surfaces that exist for tests (<c>RecordingRenderSurface</c>,
    /// <c>NullRenderSurface</c> and their records). Documenting a recording surface to a model
    /// authoring a strategy invites it to construct one.</para>
    /// </summary>
    private static readonly HashSet<string> HostWiring =
    [
        nameof(AuthoredPluginBootstrap),
        nameof(AuthoredStrategyTypes),
        nameof(IPluginRegistrar),
        nameof(IStrategyEngineFactory),
        nameof(IStrategyLifecycle),
        nameof(IStrategyPlugin),
        nameof(IVisualizerLifecycle),
        nameof(NullRenderSurface),
        nameof(PluginContext),
        nameof(RecordedLine),
        nameof(RecordedRect),
        nameof(RecordedText),
        nameof(RecordingRenderSurface),
        nameof(RenderCall),
    ];

    public static string Generate()
    {
        var assembly = typeof(IStrategyKernel).Assembly;
        var docs = XmlDocumentation.LoadFor(assembly);

        var markdown = new StringBuilder();
        markdown.AppendLine("<!-- GENERATED by SdkSurfaceGenerator. Do not edit by hand.");
        markdown.AppendLine("     Reflected from DaxAlgo.Sdk so it cannot drift from the contracts it describes.");
        markdown.AppendLine("     Regenerate by running SdkSurfaceFreshnessTests. -->");
        markdown.AppendLine();
        markdown.AppendLine("# DaxAlgo SDK — the authoring surface");
        markdown.AppendLine();
        var version = SdkInfo.Version;
        markdown.AppendLine(
            "Every public member below is available to an authored strategy or visualizer. "
            + $"SDK {version}.");
        markdown.AppendLine();

        var types = assembly.GetExportedTypes()
            .Where(t => !t.IsNested && !HostWiring.Contains(t.Name))
            .ToLookup(Section);

        foreach (var section in Sections)
        {
            var members = types[section].OrderBy(t => t.Name, StringComparer.Ordinal).ToArray();
            if (members.Length == 0) continue;

            markdown.AppendLine($"## {section}");
            markdown.AppendLine();
            foreach (var type in members) AppendType(markdown, type, docs);
        }

        return markdown.ToString();
    }

    /// <summary>Writes the surface to <paramref name="repositoryRoot"/>, creating the folder. Returns
    /// true when the bytes changed, so a caller can tell "regenerated" from "already current".</summary>
    public static bool WriteTo(string repositoryRoot)
    {
        var path = Path.Combine(repositoryRoot, RelativePath.Replace('/', Path.DirectorySeparatorChar));
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);

        var generated = Generate();
        // Compare normalised, so a checkout with different line endings is not perpetually "stale".
        if (File.Exists(path) && Normalize(File.ReadAllText(path)) == Normalize(generated))
            return false;

        File.WriteAllText(path, generated);
        return true;
    }

    public static string Normalize(string text) => text.Replace("\r\n", "\n").TrimEnd();

    private static string Section(Type type)
    {
        if (type == typeof(IStrategyKernel) || type == typeof(IVisualizer))
            return Sections[0];
        if (type == typeof(IRenderSurface))
            return Sections[1];
        if (type.Namespace == "DaxAlgo.Sdk.Quant")
            return Sections[2];
        if (type.Namespace == "DaxAlgo.Sdk.Drawing")
            return Sections[3];
        return Sections[4];
    }

    /// <summary>
    /// An options record: a struct carrying a static <c>Default</c> of its own type.
    ///
    /// <para>Detected structurally rather than by the <c>Options</c> suffix, so the rule holds for a type
    /// somebody names differently and does not fire on a type that merely ends that way.</para>
    /// </summary>
    private static bool IsOptionsRecord(Type type) =>
        type.IsValueType
        && type.GetProperty("Default", BindingFlags.Public | BindingFlags.Static) is { } d
        && d.PropertyType == type;

    private static void AppendType(StringBuilder markdown, Type type, XmlDocumentation docs)
    {
        // Options records are compacted to one line each.
        //
        // The widget library nearly doubled this document — and this document is the system prompt, paid
        // for on the first turn of every session and re-read from cache on all the others, including
        // sessions for a headless kernel that draws nothing. Spelling out every field of every options
        // record, twice, would have cost more per session than the widgets save in generated code, which
        // would make a library built to reduce token burn increase it.
        //
        // What a model needs in order to CALL a widget is the Draw signature and the knowledge that an
        // options record exists with a sane Default. What each field means is what the drawing skill is
        // for, and the skill is loaded only when the brief is about a picture.
        if (IsOptionsRecord(type))
        {
            var fields = type
                .GetProperties(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly)
                .Select(p => p.Name)
                .OrderBy(name => name, StringComparer.Ordinal);

            markdown.AppendLine(
                $"- `{TypeName(type)}` — {Inline(Lead(docs.Summary(MemberKey(type))) ?? "Options.")} "
                + $"Fields: {string.Join(", ", fields)}. Use `{TypeName(type)}.Default`, never `new()`.");
            markdown.AppendLine();
            return;
        }

        markdown.AppendLine($"### `{TypeName(type)}`");
        markdown.AppendLine();

        // Widgets and estimators get their lead paragraph only. There are a lot of them, each with
        // several paragraphs of rationale, and rationale is what the on-demand skills are for — loaded
        // when the brief calls for a picture or for maths, rather than carried by every session
        // including the ones that need neither. The contracts an author must not get wrong keep their
        // full text.
        var summary = docs.Summary(MemberKey(type));
        var section = Section(type);
        if (section == Sections[2] || section == Sections[3]) summary = Lead(summary);

        if (summary is not null)
        {
            markdown.AppendLine(summary.Replace(
                XmlDocumentation.ParagraphMark.ToString(), "\n\n", StringComparison.Ordinal));
            markdown.AppendLine();
        }

        if (type.IsEnum)
        {
            foreach (var name in Enum.GetNames(type))
            {
                var value = docs.Summary($"F:{type.FullName}.{name}");
                markdown.AppendLine(value is null ? $"- `{name}`" : $"- `{name}` — {Inline(value)}");
            }
            markdown.AppendLine();
            return;
        }

        // An estimator's Value / IsReady / Reset are the IEstimator contract, documented once on the
        // interface. Repeating all three on twenty-odd types costs sixty lines of the system prompt to
        // say the same thing twenty times, and buries the members that actually differ between them.
        var isEstimator = typeof(DaxAlgo.Sdk.Quant.IEstimator).IsAssignableFrom(type)
            && type != typeof(DaxAlgo.Sdk.Quant.IEstimator);

        var members = type
            .GetMembers(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly)
            .Where(IsInteresting)
            .Where(m => !isEstimator || m.Name is not ("Value" or "IsReady" or "Reset"))
            .OrderBy(m => m.Name, StringComparer.Ordinal)
            .ToArray();

        if (isEstimator)
        {
            markdown.AppendLine("Implements `IEstimator`: `Value`, `IsReady`, `Reset()`.");
            markdown.AppendLine();
        }

        if (members.Length == 0) return;

        markdown.AppendLine("```csharp");
        foreach (var member in members) markdown.AppendLine(Signature(member));
        markdown.AppendLine("```");
        markdown.AppendLine();

        foreach (var member in members)
        {
            var text = docs.Summary(MemberKey(member));
            if (text is not null) markdown.AppendLine($"- `{member.Name}` — {Inline(text)}");
        }
        markdown.AppendLine();
    }

    /// <summary>The first sentence of a summary — enough to say what a type is for, without the
    /// paragraphs of rationale that belong in the skill packs rather than the always-on prefix.</summary>
    /// <summary>A summary flattened onto one line — for a bullet, which cannot hold a paragraph.</summary>
    private static string Inline(string text) => text.Replace(XmlDocumentation.ParagraphMark, ' ');

    private static string? Lead(string? summary)
    {
        if (string.IsNullOrWhiteSpace(summary)) return null;

        var stop = summary.IndexOf(XmlDocumentation.ParagraphMark);
        return (stop < 0 ? summary : summary[..stop]).Trim();
    }

    private static bool IsInteresting(MemberInfo member) => member switch
    {
        // Property accessors and compiler-generated record plumbing would triple the size of this
        // document while teaching a model nothing it can act on.
        MethodInfo method => !method.IsSpecialName
            && method.Name is not ("ToString" or "GetHashCode" or "Equals" or "Deconstruct" or "<Clone>$"),
        PropertyInfo => true,
        _ => false,
    };

    private static string Signature(MemberInfo member) => member switch
    {
        PropertyInfo p => $"{TypeName(p.PropertyType)} {p.Name} {{ get; }}",
        MethodInfo m =>
            $"{TypeName(m.ReturnType)} {m.Name}("
            + string.Join(", ", m.GetParameters().Select(Parameter))
            + ")",
        _ => member.Name,
    };

    private static string Parameter(ParameterInfo p)
    {
        var text = $"{TypeName(p.ParameterType)} {p.Name}";
        // Defaults are part of the contract: they tell a model which arguments it may leave out.
        if (!p.HasDefaultValue) return text;
        return $"{text} = {p.DefaultValue switch { null => "null", bool b => b ? "true" : "false", var v => v.ToString() }}";
    }

    private static string TypeName(Type type)
    {
        if (type == typeof(void)) return "void";
        if (Nullable.GetUnderlyingType(type) is { } inner) return TypeName(inner) + "?";

        if (type.IsGenericType)
        {
            var name = type.Name[..type.Name.IndexOf('`')];
            return $"{name}<{string.Join(", ", type.GetGenericArguments().Select(TypeName))}>";
        }

        return type.Name switch
        {
            "Boolean" => "bool", "Byte" => "byte", "Double" => "double", "Int32" => "int",
            "Int64" => "long", "Single" => "float", "String" => "string", "Object" => "object",
            _ => type.Name,
        };
    }

    private static string MemberKey(MemberInfo member) => member switch
    {
        Type t => $"T:{t.FullName}",
        PropertyInfo p => $"P:{p.DeclaringType!.FullName}.{p.Name}",
        MethodInfo m => $"M:{m.DeclaringType!.FullName}.{m.Name}("
            + string.Join(",", m.GetParameters().Select(p => p.ParameterType.FullName ?? p.ParameterType.Name))
            + ")",
        _ => member.Name,
    };
}

/// <summary>The compiler's XML output, read for summaries. Absent documentation degrades to a bare
/// signature rather than failing — a missing XML file must not break a build.</summary>
internal sealed class XmlDocumentation
{
    private readonly Dictionary<string, string> _summaries;

    private XmlDocumentation(Dictionary<string, string> summaries) => _summaries = summaries;

    public static XmlDocumentation LoadFor(Assembly assembly)
    {
        var path = Path.ChangeExtension(assembly.Location, ".xml");
        var summaries = new Dictionary<string, string>(StringComparer.Ordinal);
        if (!File.Exists(path)) return new XmlDocumentation(summaries);

        foreach (var member in XDocument.Load(path).Descendants("member"))
        {
            var name = member.Attribute("name")?.Value;
            var summary = member.Element("summary");
            if (name is null || summary is null) continue;

            var text = Flatten(summary);
            if (text.Length > 0) summaries[name] = text;
        }
        return new XmlDocumentation(summaries);
    }

    public string? Summary(string key) => _summaries.GetValueOrDefault(key);

    /// <summary>Collapses the doc XML to one paragraph: <c>&lt;c&gt;</c> and <c>&lt;see&gt;</c> become
    /// backticks and whitespace is normalised.
    ///
    /// <para>Walks immediate children and recurses, rather than <c>DescendantNodes</c> — the latter
    /// yields the text inside an inline element a second time, so every <c>&lt;c&gt;</c> came out
    /// duplicated.</para></summary>
    private static string Flatten(XElement element)
    {
        var text = new StringBuilder();
        Walk(element, text);

        // Paragraph boundaries survive as a marker. The lead sentence of a summary says what a type IS;
        // the <para> blocks say why it is the way it is. Both are worth having, but only the first is
        // worth putting in a prompt prefix that is paid for on every session — so the boundary has to
        // still be there when the generator decides how much to emit.
        var lines = text.ToString().Split(ParagraphMark);
        for (var index = 0; index < lines.Length; index++)
            lines[index] = string.Join(' ', lines[index].Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries));

        return string.Join(
            ParagraphMark,
            lines.Where(line => line.Length > 0));
    }

    /// <summary>
    /// Separates paragraphs inside a flattened summary.
    ///
    /// <para>A form feed, because it is the one character that cannot already be in the text. A newline
    /// was tried first and was wrong for a reason worth recording: the source XML wraps its own doc
    /// comments across lines, so every wrap became a paragraph break and sentences were cut mid-phrase —
    /// the surface came out telling authors to "push points inside the scope with", and then, on a fresh
    /// paragraph, "`Push`."</para>
    /// </summary>
    internal const char ParagraphMark = '\f';

    /// <summary>
    /// The readable tail of a documentation reference: <c>M:DaxAlgo.Sdk.IRenderSurface.Push(Double,Double)</c>
    /// becomes <c>Push</c>.
    ///
    /// <para>The parameter list must be removed <b>before</b> splitting on dots, or the last segment is
    /// whatever the final argument type happened to be — which is how the surface first came out
    /// telling authors to "push points with `Double)`".</para>
    /// </summary>
    private static string ShortName(string? reference)
    {
        if (string.IsNullOrEmpty(reference)) return string.Empty;

        var text = reference;
        if (text.Length > 1 && text[1] == ':') text = text[2..];      // strip the T:/M:/P:/F: prefix
        var parenthesis = text.IndexOf('(');
        if (parenthesis >= 0) text = text[..parenthesis];

        return text.Split('.')[^1];
    }

    private static void Walk(XElement element, StringBuilder text)
    {
        foreach (var node in element.Nodes())
        {
            switch (node)
            {
                case XText t:
                    text.Append(t.Value);
                    break;

                case XElement { Name.LocalName: "c" or "see" or "paramref" or "seealso" } inline:
                    // A cref/name reference is usually an empty element, so the attribute carries the
                    // text.
                    var value = inline.Value.Length > 0
                        ? inline.Value
                        : ShortName((inline.Attribute("cref") ?? inline.Attribute("name"))?.Value);
                    if (value.Length > 0) text.Append('`').Append(value).Append('`');
                    break;

                case XElement { Name.LocalName: "para" } paragraph:
                    text.Append(ParagraphMark);
                    Walk(paragraph, text);
                    text.Append(ParagraphMark);
                    break;

                case XElement nested:
                    text.Append(' ');
                    Walk(nested, text);
                    break;
            }
        }
    }
}
