using System.IO;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using DaxAlgo.Blocks;

namespace TradingTerminal.Infrastructure.Strategies.Authoring.Blocks;

/// <summary>One block as the agent sees it.</summary>
/// <param name="Id">The id the planner names it by.</param>
/// <param name="Title">The one-line index entry.</param>
/// <param name="Order">Where it sits in the index.</param>
/// <param name="Markdown">The whole card.</param>
public sealed record BlockCard(string Id, string Title, int Order, string Markdown);

/// <summary>
/// Generates the block cards Hyperion is shown instead of the SDK: one short card per block, and an
/// index of one line per card.
///
/// <para><b>What a block does and needs, never how it works.</b> A card is the block's
/// <see cref="BlockCardAttribute"/> prose, each member's signature with the lead sentence of its
/// summary, and the shape of every type the block hands over or expects. Remarks, rationale and
/// implementation never reach it. The whole SDK used to be sent on every call; now a task receives the
/// index and the cards it names.</para>
///
/// <para>Reflected rather than written, for the reason <see cref="SdkSurfaceGenerator"/> gives: a
/// hand-kept description of a contract drifts from the contract. <c>BlockCardTests</c> fails when the
/// committed cards fall behind the code.</para>
/// </summary>
public static class BlockCatalogGenerator
{
    /// <summary>Where the cards are committed, relative to the repository root.</summary>
    public const string RelativeDirectory = "sdk/ai-context/blocks";

    /// <summary>The index file, relative to <see cref="RelativeDirectory"/>.</summary>
    public const string IndexFile = "index.md";

    /// <summary>The folder holding one file per card, relative to <see cref="RelativeDirectory"/>.</summary>
    public const string CardsFolder = "cards";

    private const string Banner = "<!-- GENERATED by BlockCatalogGenerator from DaxAlgo.Blocks. Do not edit; run BlockCardTests. -->";

    /// <summary>Every card, in index order.</summary>
    public static IReadOnlyList<BlockCard> Cards()
    {
        var blocks = typeof(IUnit).Assembly;
        var docs = XmlDocumentation.LoadFor(
            blocks,
            typeof(DaxAlgo.Sdk.Quant.Num).Assembly,
            typeof(TradingTerminal.Core.Domain.InstrumentId).Assembly);

        var onInterfaces = blocks.GetExportedTypes()
            .Where(type => type.IsInterface)
            .Select(type => (Attribute: type.GetCustomAttribute<BlockCardAttribute>(), Contract: (Type?)type))
            .Where(pair => pair.Attribute is not null);

        var onAssembly = blocks.GetCustomAttributes<BlockCardAttribute>()
            .Select(attribute => (Attribute: (BlockCardAttribute?)attribute, Contract: (Type?)null));

        return onInterfaces.Concat(onAssembly)
            .Select(pair => Render(pair.Attribute!, pair.Contract, docs))
            .OrderBy(card => card.Order)
            .ThenBy(card => card.Id, StringComparer.Ordinal)
            .ToArray();
    }

    /// <summary>The index: one line per card.</summary>
    public static string Index(IReadOnlyList<BlockCard> cards)
    {
        var text = new StringBuilder();
        text.AppendLine(Banner);
        text.AppendLine("# Blocks");
        text.AppendLine();
        text.AppendLine("A unit is built from these blocks. Name the ones a task needs; each has a card with its calls. `unit` is always needed.");
        text.AppendLine();
        foreach (var card in cards)
            text.AppendLine($"- `{card.Id}` — {card.Title}");
        return text.ToString();
    }

    /// <summary>Every generated file, by path relative to the repository root.</summary>
    public static IReadOnlyDictionary<string, string> Generate()
    {
        var cards = Cards();
        var files = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            [$"{RelativeDirectory}/{IndexFile}"] = Index(cards),
        };

        foreach (var card in cards)
            files[$"{RelativeDirectory}/{CardsFolder}/{card.Id}.md"] = $"{Banner}{Environment.NewLine}{card.Markdown}";

        return files;
    }

    /// <summary>
    /// Writes the index and the cards under <paramref name="repositoryRoot"/>, and deletes card files
    /// for blocks that no longer exist. Returns true when anything changed.
    /// </summary>
    public static bool WriteTo(string repositoryRoot)
    {
        var changed = false;
        var files = Generate();

        foreach (var (relative, content) in files)
        {
            var path = Path.Combine(repositoryRoot, relative.Replace('/', Path.DirectorySeparatorChar));
            Directory.CreateDirectory(Path.GetDirectoryName(path)!);

            if (File.Exists(path) && SdkSurfaceGenerator.Normalize(File.ReadAllText(path)) == SdkSurfaceGenerator.Normalize(content))
                continue;

            File.WriteAllText(path, content);
            changed = true;
        }

        // A card for a block that was removed would keep teaching it.
        var folder = Path.Combine(repositoryRoot, RelativeDirectory.Replace('/', Path.DirectorySeparatorChar), CardsFolder);
        foreach (var stale in Directory.EnumerateFiles(folder, "*.md"))
        {
            var relative = $"{RelativeDirectory}/{CardsFolder}/{Path.GetFileName(stale)}";
            if (files.ContainsKey(relative)) continue;
            File.Delete(stale);
            changed = true;
        }

        return changed;
    }

    // ── rendering ───────────────────────────────────────────────────────────────────────────────

    /// <summary>The longest description a card keeps for one type or member, in characters. Some
    /// summaries in Core were written for maintainers and run to a paragraph; a card needs the gist.</summary>
    internal const int MaximumLead = 180;

    private static readonly NullabilityInfoContext Nullability = new();

    private static BlockCard Render(BlockCardAttribute attribute, Type? contract, XmlDocumentation docs)
    {
        var text = new StringBuilder();
        text.AppendLine($"## {attribute.Id} — {attribute.Title}");
        text.AppendLine();
        if (attribute.Does.Length > 0) text.AppendLine($"Does: {attribute.Does}");
        if (attribute.Needs.Length > 0) text.AppendLine($"Needs: {attribute.Needs}");

        if (contract is not null)
        {
            text.AppendLine();
            text.AppendLine($"Calls on `{SdkSurfaceGenerator.TypeName(contract)}`:");
            foreach (var member in Members(contract))
                text.AppendLine($"- `{Signature(member)}`" + Suffix(Lead(docs, member)));
        }

        if (attribute.Types.Length > 0)
        {
            text.AppendLine();
            text.AppendLine("Types:");
            foreach (var type in attribute.Types)
                foreach (var line in Describe(type, docs))
                    text.AppendLine(line);
        }

        if (attribute.Limits.Length > 0)
        {
            text.AppendLine();
            text.AppendLine($"Limits: {attribute.Limits}");
        }

        return new BlockCard(attribute.Id, attribute.Title, attribute.Order, text.ToString());
    }

    /// <summary>The lines describing one type: its shape, and nothing about how it works.</summary>
    private static IEnumerable<string> Describe(Type type, XmlDocumentation docs)
    {
        var name = SdkSurfaceGenerator.TypeName(type);
        var lead = Lead(docs, type);

        if (type.IsEnum)
        {
            yield return $"- `{name}: {string.Join(" | ", Enum.GetNames(type))}`" + Suffix(lead);
            yield break;
        }

        var methods = Members(type).OfType<MethodInfo>().ToArray();

        // A positional record is its constructor. Checked first: OhlcvBar also has a static factory,
        // and describing it by that would hide the fields a unit actually reads.
        var positional = IsRecord(type) ? PrimaryConstructor(type) : null;

        // A factory type is described by its factories: StrategyParameter is built, never newed.
        var factories = methods.Where(m => m.IsStatic && m.ReturnType == type).ToArray();
        if (positional is null && factories.Length > 0)
        {
            yield return $"- `{name}`" + Suffix(lead);
            foreach (var factory in factories)
                yield return $"  - `{name}.{Call(factory)}`";
            yield break;
        }

        // A static class of helpers: every call, with what it does.
        if (type.IsAbstract && type.IsSealed)
        {
            yield return $"- `{name}`" + Suffix(lead);
            foreach (var method in methods.Where(m => m.IsStatic))
                yield return $"  - `{Signature(method)}`" + Suffix(Lead(docs, method));
            yield break;
        }

        var estimator = typeof(DaxAlgo.Sdk.Quant.IEstimator).IsAssignableFrom(type) && !type.IsInterface;

        var shape = positional is not null
            ? $"{name}({Parameters(positional)})"
            : type.IsInterface
                ? name
                : string.Join(" / ", type.GetConstructors().Where(c => c.IsPublic).Select(c => $"new {name}({Parameters(c)})"))
                  is { Length: > 0 } constructors ? constructors : name;

        var positionalNames = positional?.GetParameters()
            .Select(p => p.Name ?? string.Empty)
            .ToHashSet(StringComparer.OrdinalIgnoreCase) ?? [];

        // What a caller reads or calls beyond the constructor. Names only for properties; calls for
        // methods — the parameter list is the part a model would otherwise guess.
        var extras = Members(type)
            .Where(member => member is not ConstructorInfo)
            .Where(member => member is not MethodInfo { IsStatic: true })
            .Where(member => !positionalNames.Contains(member.Name))
            .Where(member => !estimator || member.Name is not ("Value" or "IsReady" or "Reset"))
            .Select(member => member is MethodInfo method ? Call(method) : member.Name)
            .Distinct(StringComparer.Ordinal)
            .ToArray();

        var tail = new List<string>();
        if (estimator) tail.Add("IEstimator");
        tail.AddRange(extras);

        yield return $"- `{shape}`"
            + Suffix(lead)
            + (tail.Count == 0 ? string.Empty : $" · {string.Join(" · ", tail.Select(t => $"`{t}`"))}");
    }

    /// <summary>Properties first, then constructors, then methods, each in declaration order.</summary>
    private static IEnumerable<MemberInfo> Members(Type type) => type
        .GetMembers(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly)
        .Where(SdkSurfaceGenerator.IsInteresting)
        .OrderBy(member => member switch { PropertyInfo => 0, ConstructorInfo => 1, _ => 2 })
        .ThenBy(member => member.MetadataToken);

    private static bool IsRecord(Type type) =>
        type.GetMethod("PrintMembers", BindingFlags.NonPublic | BindingFlags.Instance) is not null;

    /// <summary>The constructor whose parameters are the record's positional properties.</summary>
    private static ConstructorInfo? PrimaryConstructor(Type type) => type.GetConstructors()
        .Where(c => c.IsPublic && c.GetParameters().Length > 0)
        .Where(c => c.GetParameters().All(p => type.GetProperty(p.Name ?? string.Empty) is not null))
        .OrderByDescending(c => c.GetParameters().Length)
        .FirstOrDefault();

    /// <summary>A member as it is called, with nullable reference types marked — "or null" in a summary
    /// is easy to miss, a <c>?</c> on the return type is not.</summary>
    private static string Signature(MemberInfo member) => member switch
    {
        PropertyInfo p => $"{Name(p.PropertyType, Nullability.Create(p))} {p.Name} {{ get; }}",
        MethodInfo m => $"{Name(m.ReturnType, Nullability.Create(m.ReturnParameter))} {Call(m)}",
        ConstructorInfo c => $"new {SdkSurfaceGenerator.TypeName(c.DeclaringType!)}({Parameters(c)})",
        _ => member.Name,
    };

    private static string Name(Type type, NullabilityInfo nullability) =>
        type.IsByRef
            ? SdkSurfaceGenerator.TypeName(type.GetElementType()!)
            : SdkSurfaceGenerator.TypeName(type)
              + (!type.IsValueType && nullability.ReadState == NullabilityState.Nullable ? "?" : string.Empty);

    private static string Parameters(MethodBase method) =>
        string.Join(", ", method.GetParameters().Select(p =>
        {
            var text = $"{(p.IsOut ? "out " : string.Empty)}{Name(p.ParameterType, Nullability.Create(p))} {p.Name}";
            return p.HasDefaultValue ? $"{text} = {Literal(p)}" : text;
        }));

    /// <summary>A default value as C# would write it.</summary>
    private static string Literal(ParameterInfo parameter) => parameter.DefaultValue switch
    {
        // `CancellationToken ct = default` reflects as a null default on a struct.
        null when parameter.ParameterType.IsValueType && Nullable.GetUnderlyingType(parameter.ParameterType) is null => "default",
        null => "null",
        string s => $"\"{s}\"",
        bool b => b ? "true" : "false",
        Enum e => $"{SdkSurfaceGenerator.TypeName(e.GetType())}.{e}",
        IFormattable f => f.ToString(null, System.Globalization.CultureInfo.InvariantCulture),
        var v => v.ToString() ?? "null",
    };

    private static string Call(MethodInfo method) => $"{method.Name}({Parameters(method)})";

    private static string Suffix(string? sentence) => sentence is null ? string.Empty : $" — {sentence}";

    /// <summary>The documented gist of a type or member, found by its real documentation id.</summary>
    private static string? Lead(XmlDocumentation docs, MemberInfo member)
    {
        var sentence = FirstSentence(docs.Summary(DocumentationId(member)));
        if (sentence is null || sentence.Length <= MaximumLead) return sentence;

        var cut = sentence.LastIndexOf(' ', MaximumLead);
        return sentence[..(cut > 0 ? cut : MaximumLead)].TrimEnd(',', ';', ':') + "…";
    }

    /// <summary>The first sentence of a summary's first paragraph: what the thing is, and no more.</summary>
    internal static string? FirstSentence(string? summary)
    {
        if (string.IsNullOrWhiteSpace(summary)) return null;

        var paragraph = summary.Split(XmlDocumentation.ParagraphMark, StringSplitOptions.RemoveEmptyEntries)[0].Trim();
        var match = SentenceEnd.Match(paragraph);
        return match.Success ? paragraph[..(match.Index + 1)].Trim() : paragraph;
    }

    /// <summary>A full stop followed by a new sentence — not the one inside "e.g." or a decimal.</summary>
    private static readonly Regex SentenceEnd = new(@"(?<!\b(?:e\.g|i\.e|vs|etc))\.\s+(?=[A-Z`])", RegexOptions.Compiled);

    /// <summary>
    /// The id the compiler's XML documentation files a member under.
    ///
    /// <para>Written out rather than reused from <see cref="SdkSurfaceGenerator"/>, whose key builds a
    /// generic parameter from <c>Type.FullName</c> and always adds parentheses. The documentation file
    /// writes <c>System.Action{TradingTerminal.Core.Domain.Quote}</c> and omits the parentheses on a
    /// parameterless method, so every handler and every <c>Reset()</c> came back undocumented.</para>
    /// </summary>
    internal static string DocumentationId(MemberInfo member) => member switch
    {
        Type type => $"T:{DocumentationType(type)}",
        PropertyInfo property => $"P:{DocumentationType(property.DeclaringType!)}.{property.Name}",
        ConstructorInfo constructor => $"M:{DocumentationType(constructor.DeclaringType!)}.#ctor{DocumentationParameters(constructor)}",
        MethodInfo method => $"M:{DocumentationType(method.DeclaringType!)}.{method.Name}"
            + (method.IsGenericMethod ? $"``{method.GetGenericArguments().Length}" : string.Empty)
            + DocumentationParameters(method),
        _ => member.Name,
    };

    private static string DocumentationParameters(MethodBase method)
    {
        var parameters = method.GetParameters();
        return parameters.Length == 0
            ? string.Empty
            : $"({string.Join(",", parameters.Select(p => DocumentationType(p.ParameterType)))})";
    }

    private static string DocumentationType(Type type)
    {
        if (type.IsGenericParameter)
            return type.DeclaringMethod is not null ? $"``{type.GenericParameterPosition}" : $"`{type.GenericParameterPosition}";
        if (type.IsByRef) return DocumentationType(type.GetElementType()!) + "@";
        if (type.IsArray) return DocumentationType(type.GetElementType()!) + "[]";

        if (type.IsGenericType && !type.IsGenericTypeDefinition)
        {
            var definition = type.GetGenericTypeDefinition().FullName!;
            return $"{definition[..definition.IndexOf('`')]}{{{string.Join(",", type.GetGenericArguments().Select(DocumentationType))}}}";
        }

        return (type.FullName ?? type.Name).Replace('+', '.');
    }
}
